services:
  web-decoy:
    image: ghcr.io/andreicscs/honeywire-webrouterdecoy:latest
    container_name: hw-web-decoy
    build:
      context: ../../..
      dockerfile: Sensors/official/WebRouterDecoy/Dockerfile
    restart: unless-stopped
    
    # Preserves the real Source IP of the attacker.
    network_mode: "host"
    # Required to bind to low ports
    user: "0:0"

    # --- SECURITY SANDBOX ---
    read_only: true
    cap_drop: ["ALL"]
    security_opt: ["no-new-privileges:true"]
    # ------------------------

    environment:
      - HW_HUB_ENDPOINT=http://127.0.0.1:8080 
      - HW_HUB_KEY=change_this_to_a_secure_random_string
      - HW_SENSOR_ID=production-web-decoy-01
      - HW_TEST_MODE=false
      
      # Web Honeypot Configuration
      - HW_BIND_PORT=8081
      - HW_ROUTER_BRAND=Cisco