services:
  tcp-tripwire:
    # Option A: Pull the pre-built image from GHCR (Uncomment lines below to use)
    # image: ghcr.io/andreicscs/honeywire-tcptripwire:latest
    
    # Option B: Build locally from source (Comment lines below if you want to use the pre-built image)
    build:
      context: ../../../ 
      dockerfile: Sensors/official/TcpTripWire/Dockerfile
    
    container_name: hw-tcp-tripwire
    restart: unless-stopped
    
    # CRITICAL: Binds directly to the host machine's network to capture real source IPs
    network_mode: "host" 
    
    env_file: 
      - .env